name: Process New Question

on:
  repository_dispatch:
    types: [new_question]

jobs:
  process-question:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create new issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "${{ github.event.client_payload.question }}",
              "body": "匿名提问",
              "labels": ["question"]
            }'
